apiVersion: v1
kind: PersistentVolume
metadata:
 name: glusterfs-pv
spec:
 capacity:
  storage: 1Gi
 accessModes:
 - ReadWriteMany
 glusterfs:
  endpoints: glusterfs-cluster
  path: /gv0
  readOnly: false
 persistentVolumeReclaimPolicy: Retain
