apiVersion: apps/v1
kind: Deployment
metadata:
 name: facialrec-deployment
 labels:
  app: facialrec
spec:
 replicas: 0
 selector:
  matchLabels:
   app: facialrec
 template:
  metadata:
   labels:
    app: facialrec
  spec:
   affinity:
    nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: device
          operator: In
          values:
          - RedHat
   volumes:
    - name: facialrec-storage
      hostPath:
       path: /gv0
       type: Directory
   containers:
   - image: coffeybean60/facialrec
     name: facialrec
     ports:
     - containerPort: 8080
     resources:
      requests:
       memory: 2G
       cpu: 2
      limits:
       memory: 3G
       cpu: 2
     volumeMounts:
      - mountPath: /gv0
        name: facialrec-storage
